import{Link}from'react-router-dom';
export function Badge({value}){const s=String(value||'').toLowerCase();return <span className={`badge badge-${s}`}>{String(value||'').replaceAll('_',' ')}</span>}
export function Button({children,className='',...props}){return <button className={`button ${className}`} {...props}>{children}</button>}
export function Empty({title='Nothing to show yet',body='When there is activity, it will appear here.'}){return <div className="empty"><span className="empty-icon">◇</span><strong>{title}</strong><span>{body}</span></div>}
export function PageTitle({title,subtitle,action}){return <div className="page-title"><div><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div>{action}</div>}
export function Field({label,error,...props}){return <label className="field"><span>{label}</span><input {...props}/>{error&&<small className="field-error">{error}</small>}</label>}
export function Select({label,children,...props}){return <label className="field"><span>{label}</span><select {...props}>{children}</select></label>}
export function DataTable({columns,rows,empty='No records found'}){if(!rows?.length)return <Empty title={empty}/>;return <div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c.key}>{c.label}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={row.id||i}>{columns.map(c=><td key={c.key}>{c.render?c.render(row):row[c.key]}</td>)}</tr>)}</tbody></table></div>}
export function GrievanceTable({rows}){return <DataTable rows={rows} empty="No grievances match these filters" columns={[{key:'referenceNo',label:'Reference',render:g=><Link className="text-link" to={`/app/grievances/${g.id}`}>{g.referenceNo}</Link>},{key:'title',label:'Grievance',render:g=><div className="table-primary">{g.title}<span>{g.category?.name||'—'}</span></div>},{key:'priority',label:'Priority',render:g=><Badge value={g.priority}/>},{key:'status',label:'Status',render:g=><Badge value={g.status}/>},{key:'createdAt',label:'Submitted',render:g=>new Date(g.createdAt).toLocaleDateString()}]}/>}
